<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<!-- Document definition -->
<!DOCTYPE MEME[
<!ELEMENT MEME (
  training_set,
  model, 
  motifs, 
  scanned_sites_summary?
)>
<!ATTLIST MEME 
  version CDATA #REQUIRED
  release CDATA #REQUIRED
>
<!-- Training-set elements -->
<!ELEMENT training_set (alphabet, ambigs, sequence+, letter_frequencies)>
<!ATTLIST training_set datafile CDATA #REQUIRED length CDATA #REQUIRED>
<!ELEMENT alphabet (letter+)>
<!ATTLIST alphabet id (amino-acid|nucleotide) #REQUIRED
                   length CDATA #REQUIRED>
<!ELEMENT ambigs (letter+)>
<!ELEMENT letter EMPTY>
<!ATTLIST letter id ID #REQUIRED>
<!ATTLIST letter symbol CDATA #REQUIRED>
<!ELEMENT sequence EMPTY>
<!ATTLIST sequence id ID #REQUIRED
                   name CDATA #REQUIRED
                   length CDATA #REQUIRED
                   weight CDATA #REQUIRED
>
<!ELEMENT letter_frequencies (alphabet_array)>

<!-- Model elements -->
<!ELEMENT model (
  command_line,
  host,
  type,
  nmotifs,
  evalue_threshold,
  object_function,
  min_width,
  max_width,
  minic,
  wg,
  ws,
  endgaps,
  minsites,
  maxsites,
  wnsites,
  prob,
  spmap,
  spfuzz,
  prior,
  beta,
  maxiter,
  distance,
  num_sequences,
  num_positions,
  seed,
  seqfrac,
  strands,
  priors_file,
  reason_for_stopping,
  background_frequencies
)>
<!ELEMENT command_line (#PCDATA)*>
<!ELEMENT host (#PCDATA)*>
<!ELEMENT type (#PCDATA)*>
<!ELEMENT nmotifs (#PCDATA)*>
<!ELEMENT evalue_threshold (#PCDATA)*>
<!ELEMENT object_function (#PCDATA)*>
<!ELEMENT min_width (#PCDATA)*>
<!ELEMENT max_width (#PCDATA)*>
<!ELEMENT minic (#PCDATA)*>
<!ELEMENT wg (#PCDATA)*>
<!ELEMENT ws (#PCDATA)*>
<!ELEMENT endgaps (#PCDATA)*>
<!ELEMENT minsites (#PCDATA)*>
<!ELEMENT maxsites (#PCDATA)*>
<!ELEMENT wnsites (#PCDATA)*>
<!ELEMENT prob (#PCDATA)*>
<!ELEMENT spmap (#PCDATA)*>
<!ELEMENT spfuzz (#PCDATA)*>
<!ELEMENT prior (#PCDATA)*>
<!ELEMENT beta (#PCDATA)*>
<!ELEMENT maxiter (#PCDATA)*>
<!ELEMENT distance (#PCDATA)*>
<!ELEMENT num_sequences (#PCDATA)*>
<!ELEMENT num_positions (#PCDATA)*>
<!ELEMENT seed (#PCDATA)*>
<!ELEMENT seqfrac (#PCDATA)*>
<!ELEMENT strands (#PCDATA)*>
<!ELEMENT priors_file (#PCDATA)*>
<!ELEMENT reason_for_stopping (#PCDATA)*>
<!ELEMENT background_frequencies (alphabet_array)>
<!ATTLIST background_frequencies source CDATA #REQUIRED>

<!-- Motif elements -->
<!ELEMENT motifs (motif+)>
<!ELEMENT motif (scores, probabilities, regular_expression?, contributing_sites)>
<!ATTLIST motif id ID #REQUIRED
                name CDATA #REQUIRED
                width CDATA #REQUIRED
                sites CDATA #REQUIRED
                llr CDATA #REQUIRED
                ic CDATA #REQUIRED
                re CDATA #REQUIRED
                bayes_threshold CDATA #REQUIRED
                e_value CDATA #REQUIRED
                elapsed_time CDATA #REQUIRED
                url CDATA ""
>
<!ELEMENT scores (alphabet_matrix)>
<!ELEMENT probabilities (alphabet_matrix)>
<!ELEMENT regular_expression (#PCDATA)*>

<!-- Contributing site elements -->
<!-- Contributing sites are motif occurences found during the motif discovery phase -->
<!ELEMENT contributing_sites (contributing_site+)>
<!ELEMENT contributing_site (left_flank, site, right_flank)>
<!ATTLIST contributing_site sequence_id IDREF #REQUIRED
                          position CDATA #REQUIRED
                          strand (plus|minus|none) 'none'
                          pvalue CDATA #REQUIRED
>
<!-- The left_flank contains the sequence for 10 bases to the left of the motif start -->
<!ELEMENT left_flank (#PCDATA)>
<!-- The site contains the sequence for the motif instance -->
<!ELEMENT site (letter_ref+)>
<!-- The right_flank contains the sequence for 10 bases to the right of the motif end -->
<!ELEMENT right_flank (#PCDATA)>

<!-- Scanned site elements -->
<!-- Scanned sites are motif occurences found during the sequence scan phase -->
<!ELEMENT scanned_sites_summary (scanned_sites+)>
<!ATTLIST scanned_sites_summary p_thresh CDATA #REQUIRED>
<!ELEMENT scanned_sites (scanned_site*)>
<!ATTLIST scanned_sites sequence_id IDREF #REQUIRED
                        pvalue CDATA #REQUIRED
                        num_sites CDATA #REQUIRED>
<!ELEMENT scanned_site EMPTY>
<!ATTLIST scanned_site  motif_id IDREF #REQUIRED
                        strand (plus|minus|none) 'none'
                        position CDATA #REQUIRED
                        pvalue CDATA #REQUIRED>

<!-- Utility elements -->
<!-- A reference to a letter in the alphabet -->
<!ELEMENT letter_ref EMPTY>
<!ATTLIST letter_ref letter_id IDREF #REQUIRED>
<!-- A alphabet-array contains one floating point value for each letter in an alphabet -->
<!ELEMENT alphabet_array (value+)>
<!ELEMENT value (#PCDATA)>
<!ATTLIST value letter_id IDREF #REQUIRED>

<!-- A alphabet_matrix contains one alphabet_array for each position in a motif -->
<!ELEMENT alphabet_matrix (alphabet_array+)>

]>
<!-- Begin document body -->
<MEME version="4.8.1" release="Tue Feb  7 14:03:40 EST 2012">
<training_set datafile="/lustre/mib-cri/carrol09/Work/PipelinePracticeSet/Trial/20121114_MontoyaAR_DN_Hes6ChIP/Peaks/Macs/Motif/MCF7/Denovo/seqs-centered" length="500">
<alphabet id="nucleotide" length="4">
<letter id="letter_A" symbol="A"/>
<letter id="letter_C" symbol="C"/>
<letter id="letter_G" symbol="G"/>
<letter id="letter_T" symbol="T"/>
</alphabet>
<ambigs>
<letter id="letter_B" symbol="B"/>
<letter id="letter_D" symbol="D"/>
<letter id="letter_H" symbol="H"/>
<letter id="letter_K" symbol="K"/>
<letter id="letter_M" symbol="M"/>
<letter id="letter_N" symbol="N"/>
<letter id="letter_R" symbol="R"/>
<letter id="letter_S" symbol="S"/>
<letter id="letter_U" symbol="U"/>
<letter id="letter_V" symbol="V"/>
<letter id="letter_W" symbol="W"/>
<letter id="letter_Y" symbol="Y"/>
<letter id="letter_star" symbol="*"/>
<letter id="letter_-" symbol="-"/>
<letter id="letter_X" symbol="X"/>
</ambigs>
<sequence id="sequence_0" name="MACS_peak_263" length="100" weight="1.000000" />
<sequence id="sequence_1" name="MACS_peak_183" length="100" weight="1.000000" />
<sequence id="sequence_2" name="MACS_peak_374" length="100" weight="1.000000" />
<sequence id="sequence_3" name="MACS_peak_848" length="100" weight="1.000000" />
<sequence id="sequence_4" name="MACS_peak_984" length="100" weight="1.000000" />
<sequence id="sequence_5" name="MACS_peak_1038" length="100" weight="1.000000" />
<sequence id="sequence_6" name="MACS_peak_458" length="100" weight="1.000000" />
<sequence id="sequence_7" name="MACS_peak_177" length="100" weight="1.000000" />
<sequence id="sequence_8" name="MACS_peak_363" length="100" weight="1.000000" />
<sequence id="sequence_9" name="MACS_peak_570" length="100" weight="1.000000" />
<sequence id="sequence_10" name="MACS_peak_614" length="100" weight="1.000000" />
<sequence id="sequence_11" name="MACS_peak_677" length="100" weight="1.000000" />
<sequence id="sequence_12" name="MACS_peak_1068" length="100" weight="1.000000" />
<sequence id="sequence_13" name="MACS_peak_158" length="100" weight="1.000000" />
<sequence id="sequence_14" name="MACS_peak_173" length="100" weight="1.000000" />
<sequence id="sequence_15" name="MACS_peak_198" length="100" weight="1.000000" />
<sequence id="sequence_16" name="MACS_peak_199" length="100" weight="1.000000" />
<sequence id="sequence_17" name="MACS_peak_287" length="100" weight="1.000000" />
<sequence id="sequence_18" name="MACS_peak_306" length="100" weight="1.000000" />
<sequence id="sequence_19" name="MACS_peak_315" length="100" weight="1.000000" />
<sequence id="sequence_20" name="MACS_peak_316" length="100" weight="1.000000" />
<sequence id="sequence_21" name="MACS_peak_319" length="100" weight="1.000000" />
<sequence id="sequence_22" name="MACS_peak_320" length="100" weight="1.000000" />
<sequence id="sequence_23" name="MACS_peak_324" length="100" weight="1.000000" />
<sequence id="sequence_24" name="MACS_peak_343" length="100" weight="1.000000" />
<sequence id="sequence_25" name="MACS_peak_395" length="100" weight="1.000000" />
<sequence id="sequence_26" name="MACS_peak_425" length="100" weight="1.000000" />
<sequence id="sequence_27" name="MACS_peak_434" length="100" weight="1.000000" />
<sequence id="sequence_28" name="MACS_peak_444" length="100" weight="1.000000" />
<sequence id="sequence_29" name="MACS_peak_468" length="100" weight="1.000000" />
<sequence id="sequence_30" name="MACS_peak_470" length="100" weight="1.000000" />
<sequence id="sequence_31" name="MACS_peak_496" length="100" weight="1.000000" />
<sequence id="sequence_32" name="MACS_peak_501" length="100" weight="1.000000" />
<sequence id="sequence_33" name="MACS_peak_520" length="100" weight="1.000000" />
<sequence id="sequence_34" name="MACS_peak_526" length="100" weight="1.000000" />
<sequence id="sequence_35" name="MACS_peak_530" length="100" weight="1.000000" />
<sequence id="sequence_36" name="MACS_peak_532" length="100" weight="1.000000" />
<sequence id="sequence_37" name="MACS_peak_550" length="100" weight="1.000000" />
<sequence id="sequence_38" name="MACS_peak_596" length="100" weight="1.000000" />
<sequence id="sequence_39" name="MACS_peak_600" length="100" weight="1.000000" />
<sequence id="sequence_40" name="MACS_peak_623" length="100" weight="1.000000" />
<sequence id="sequence_41" name="MACS_peak_628" length="100" weight="1.000000" />
<sequence id="sequence_42" name="MACS_peak_687" length="100" weight="1.000000" />
<sequence id="sequence_43" name="MACS_peak_695" length="100" weight="1.000000" />
<sequence id="sequence_44" name="MACS_peak_696" length="100" weight="1.000000" />
<sequence id="sequence_45" name="MACS_peak_726" length="100" weight="1.000000" />
<sequence id="sequence_46" name="MACS_peak_760" length="100" weight="1.000000" />
<sequence id="sequence_47" name="MACS_peak_799" length="100" weight="1.000000" />
<sequence id="sequence_48" name="MACS_peak_808" length="100" weight="1.000000" />
<sequence id="sequence_49" name="MACS_peak_815" length="100" weight="1.000000" />
<sequence id="sequence_50" name="MACS_peak_818" length="100" weight="1.000000" />
<sequence id="sequence_51" name="MACS_peak_820" length="100" weight="1.000000" />
<sequence id="sequence_52" name="MACS_peak_847" length="100" weight="1.000000" />
<sequence id="sequence_53" name="MACS_peak_866" length="100" weight="1.000000" />
<sequence id="sequence_54" name="MACS_peak_870" length="100" weight="1.000000" />
<sequence id="sequence_55" name="MACS_peak_871" length="100" weight="1.000000" />
<sequence id="sequence_56" name="MACS_peak_874" length="100" weight="1.000000" />
<sequence id="sequence_57" name="MACS_peak_1054" length="100" weight="1.000000" />
<sequence id="sequence_58" name="MACS_peak_1077" length="100" weight="1.000000" />
<sequence id="sequence_59" name="MACS_peak_605" length="100" weight="1.000000" />
<sequence id="sequence_60" name="MACS_peak_267" length="100" weight="1.000000" />
<sequence id="sequence_61" name="MACS_peak_356" length="100" weight="1.000000" />
<sequence id="sequence_62" name="MACS_peak_853" length="100" weight="1.000000" />
<sequence id="sequence_63" name="MACS_peak_467" length="100" weight="1.000000" />
<sequence id="sequence_64" name="MACS_peak_604" length="100" weight="1.000000" />
<sequence id="sequence_65" name="MACS_peak_301" length="100" weight="1.000000" />
<sequence id="sequence_66" name="MACS_peak_724" length="100" weight="1.000000" />
<sequence id="sequence_67" name="MACS_peak_463" length="100" weight="1.000000" />
<sequence id="sequence_68" name="MACS_peak_750" length="100" weight="1.000000" />
<sequence id="sequence_69" name="MACS_peak_653" length="100" weight="1.000000" />
<sequence id="sequence_70" name="MACS_peak_75" length="100" weight="1.000000" />
<sequence id="sequence_71" name="MACS_peak_840" length="100" weight="1.000000" />
<sequence id="sequence_72" name="MACS_peak_540" length="100" weight="1.000000" />
<sequence id="sequence_73" name="MACS_peak_252" length="100" weight="1.000000" />
<sequence id="sequence_74" name="MACS_peak_859" length="100" weight="1.000000" />
<sequence id="sequence_75" name="MACS_peak_239" length="100" weight="1.000000" />
<sequence id="sequence_76" name="MACS_peak_914" length="100" weight="1.000000" />
<sequence id="sequence_77" name="MACS_peak_737" length="100" weight="1.000000" />
<sequence id="sequence_78" name="MACS_peak_765" length="100" weight="1.000000" />
<sequence id="sequence_79" name="MACS_peak_718" length="100" weight="1.000000" />
<sequence id="sequence_80" name="MACS_peak_829" length="100" weight="1.000000" />
<sequence id="sequence_81" name="MACS_peak_1072" length="100" weight="1.000000" />
<sequence id="sequence_82" name="MACS_peak_1018" length="100" weight="1.000000" />
<sequence id="sequence_83" name="MACS_peak_140" length="100" weight="1.000000" />
<sequence id="sequence_84" name="MACS_peak_655" length="100" weight="1.000000" />
<sequence id="sequence_85" name="MACS_peak_943" length="100" weight="1.000000" />
<sequence id="sequence_86" name="MACS_peak_981" length="100" weight="1.000000" />
<sequence id="sequence_87" name="MACS_peak_507" length="100" weight="1.000000" />
<sequence id="sequence_88" name="MACS_peak_300" length="100" weight="1.000000" />
<sequence id="sequence_89" name="MACS_peak_795" length="100" weight="1.000000" />
<sequence id="sequence_90" name="MACS_peak_896" length="100" weight="1.000000" />
<sequence id="sequence_91" name="MACS_peak_857" length="100" weight="1.000000" />
<sequence id="sequence_92" name="MACS_peak_250" length="100" weight="1.000000" />
<sequence id="sequence_93" name="MACS_peak_652" length="100" weight="1.000000" />
<sequence id="sequence_94" name="MACS_peak_312" length="100" weight="1.000000" />
<sequence id="sequence_95" name="MACS_peak_553" length="100" weight="1.000000" />
<sequence id="sequence_96" name="MACS_peak_302" length="100" weight="1.000000" />
<sequence id="sequence_97" name="MACS_peak_396" length="100" weight="1.000000" />
<sequence id="sequence_98" name="MACS_peak_1092" length="100" weight="1.000000" />
<sequence id="sequence_99" name="MACS_peak_237" length="100" weight="1.000000" />
<sequence id="sequence_100" name="MACS_peak_59" length="100" weight="1.000000" />
<sequence id="sequence_101" name="MACS_peak_577" length="100" weight="1.000000" />
<sequence id="sequence_102" name="MACS_peak_556" length="100" weight="1.000000" />
<sequence id="sequence_103" name="MACS_peak_171" length="100" weight="1.000000" />
<sequence id="sequence_104" name="MACS_peak_805" length="100" weight="1.000000" />
<sequence id="sequence_105" name="MACS_peak_660" length="100" weight="1.000000" />
<sequence id="sequence_106" name="MACS_peak_1053" length="100" weight="1.000000" />
<sequence id="sequence_107" name="MACS_peak_1089" length="100" weight="1.000000" />
<sequence id="sequence_108" name="MACS_peak_533" length="100" weight="1.000000" />
<sequence id="sequence_109" name="MACS_peak_823" length="100" weight="1.000000" />
<sequence id="sequence_110" name="MACS_peak_305" length="100" weight="1.000000" />
<sequence id="sequence_111" name="MACS_peak_490" length="100" weight="1.000000" />
<sequence id="sequence_112" name="MACS_peak_217" length="100" weight="1.000000" />
<sequence id="sequence_113" name="MACS_peak_821" length="100" weight="1.000000" />
<sequence id="sequence_114" name="MACS_peak_537" length="100" weight="1.000000" />
<sequence id="sequence_115" name="MACS_peak_288" length="100" weight="1.000000" />
<sequence id="sequence_116" name="MACS_peak_534" length="100" weight="1.000000" />
<sequence id="sequence_117" name="MACS_peak_643" length="100" weight="1.000000" />
<sequence id="sequence_118" name="MACS_peak_719" length="100" weight="1.000000" />
<sequence id="sequence_119" name="MACS_peak_733" length="100" weight="1.000000" />
<sequence id="sequence_120" name="MACS_peak_803" length="100" weight="1.000000" />
<sequence id="sequence_121" name="MACS_peak_837" length="100" weight="1.000000" />
<sequence id="sequence_122" name="MACS_peak_860" length="100" weight="1.000000" />
<sequence id="sequence_123" name="MACS_peak_359" length="100" weight="1.000000" />
<sequence id="sequence_124" name="MACS_peak_634" length="100" weight="1.000000" />
<sequence id="sequence_125" name="MACS_peak_91" length="100" weight="1.000000" />
<sequence id="sequence_126" name="MACS_peak_350" length="100" weight="1.000000" />
<sequence id="sequence_127" name="MACS_peak_1060" length="100" weight="1.000000" />
<sequence id="sequence_128" name="MACS_peak_676" length="100" weight="1.000000" />
<sequence id="sequence_129" name="MACS_peak_744" length="100" weight="1.000000" />
<sequence id="sequence_130" name="MACS_peak_528" length="100" weight="1.000000" />
<sequence id="sequence_131" name="MACS_peak_484" length="100" weight="1.000000" />
<sequence id="sequence_132" name="MACS_peak_246" length="100" weight="1.000000" />
<sequence id="sequence_133" name="MACS_peak_989" length="100" weight="1.000000" />
<sequence id="sequence_134" name="MACS_peak_209" length="100" weight="1.000000" />
<sequence id="sequence_135" name="MACS_peak_633" length="100" weight="1.000000" />
<sequence id="sequence_136" name="MACS_peak_780" length="100" weight="1.000000" />
<sequence id="sequence_137" name="MACS_peak_247" length="100" weight="1.000000" />
<sequence id="sequence_138" name="MACS_peak_804" length="100" weight="1.000000" />
<sequence id="sequence_139" name="MACS_peak_97" length="100" weight="1.000000" />
<sequence id="sequence_140" name="MACS_peak_1062" length="100" weight="1.000000" />
<sequence id="sequence_141" name="MACS_peak_1008" length="100" weight="1.000000" />
<sequence id="sequence_142" name="MACS_peak_508" length="100" weight="1.000000" />
<sequence id="sequence_143" name="MACS_peak_982" length="100" weight="1.000000" />
<sequence id="sequence_144" name="MACS_peak_854" length="100" weight="1.000000" />
<sequence id="sequence_145" name="MACS_peak_428" length="100" weight="1.000000" />
<sequence id="sequence_146" name="MACS_peak_654" length="100" weight="1.000000" />
<sequence id="sequence_147" name="MACS_peak_645" length="100" weight="1.000000" />
<sequence id="sequence_148" name="MACS_peak_1085" length="100" weight="1.000000" />
<sequence id="sequence_149" name="MACS_peak_963" length="100" weight="1.000000" />
<sequence id="sequence_150" name="MACS_peak_625" length="100" weight="1.000000" />
<sequence id="sequence_151" name="MACS_peak_42" length="100" weight="1.000000" />
<sequence id="sequence_152" name="MACS_peak_939" length="100" weight="1.000000" />
<sequence id="sequence_153" name="MACS_peak_322" length="100" weight="1.000000" />
<sequence id="sequence_154" name="MACS_peak_635" length="100" weight="1.000000" />
<sequence id="sequence_155" name="MACS_peak_134" length="100" weight="1.000000" />
<sequence id="sequence_156" name="MACS_peak_453" length="100" weight="1.000000" />
<sequence id="sequence_157" name="MACS_peak_1094" length="100" weight="1.000000" />
<sequence id="sequence_158" name="MACS_peak_203" length="100" weight="1.000000" />
<sequence id="sequence_159" name="MACS_peak_582" length="100" weight="1.000000" />
<sequence id="sequence_160" name="MACS_peak_597" length="100" weight="1.000000" />
<sequence id="sequence_161" name="MACS_peak_48" length="100" weight="1.000000" />
<sequence id="sequence_162" name="MACS_peak_207" length="100" weight="1.000000" />
<sequence id="sequence_163" name="MACS_peak_933" length="100" weight="1.000000" />
<sequence id="sequence_164" name="MACS_peak_970" length="100" weight="1.000000" />
<sequence id="sequence_165" name="MACS_peak_264" length="100" weight="1.000000" />
<sequence id="sequence_166" name="MACS_peak_608" length="100" weight="1.000000" />
<sequence id="sequence_167" name="MACS_peak_441" length="100" weight="1.000000" />
<sequence id="sequence_168" name="MACS_peak_289" length="100" weight="1.000000" />
<sequence id="sequence_169" name="MACS_peak_640" length="100" weight="1.000000" />
<sequence id="sequence_170" name="MACS_peak_732" length="100" weight="1.000000" />
<sequence id="sequence_171" name="MACS_peak_852" length="100" weight="1.000000" />
<sequence id="sequence_172" name="MACS_peak_717" length="100" weight="1.000000" />
<sequence id="sequence_173" name="MACS_peak_531" length="100" weight="1.000000" />
<sequence id="sequence_174" name="MACS_peak_1050" length="100" weight="1.000000" />
<sequence id="sequence_175" name="MACS_peak_85" length="100" weight="1.000000" />
<sequence id="sequence_176" name="MACS_peak_523" length="100" weight="1.000000" />
<sequence id="sequence_177" name="MACS_peak_680" length="100" weight="1.000000" />
<sequence id="sequence_178" name="MACS_peak_15" length="100" weight="1.000000" />
<sequence id="sequence_179" name="MACS_peak_647" length="100" weight="1.000000" />
<sequence id="sequence_180" name="MACS_peak_1083" length="100" weight="1.000000" />
<sequence id="sequence_181" name="MACS_peak_362" length="100" weight="1.000000" />
<sequence id="sequence_182" name="MACS_peak_578" length="100" weight="1.000000" />
<sequence id="sequence_183" name="MACS_peak_380" length="100" weight="1.000000" />
<sequence id="sequence_184" name="MACS_peak_473" length="100" weight="1.000000" />
<sequence id="sequence_185" name="MACS_peak_352" length="100" weight="1.000000" />
<sequence id="sequence_186" name="MACS_peak_174" length="100" weight="1.000000" />
<sequence id="sequence_187" name="MACS_peak_522" length="100" weight="1.000000" />
<sequence id="sequence_188" name="MACS_peak_132" length="100" weight="1.000000" />
<sequence id="sequence_189" name="MACS_peak_200" length="100" weight="1.000000" />
<sequence id="sequence_190" name="MACS_peak_836" length="100" weight="1.000000" />
<sequence id="sequence_191" name="MACS_peak_678" length="100" weight="1.000000" />
<sequence id="sequence_192" name="MACS_peak_201" length="100" weight="1.000000" />
<sequence id="sequence_193" name="MACS_peak_572" length="100" weight="1.000000" />
<sequence id="sequence_194" name="MACS_peak_465" length="100" weight="1.000000" />
<sequence id="sequence_195" name="MACS_peak_34" length="100" weight="1.000000" />
<sequence id="sequence_196" name="MACS_peak_639" length="100" weight="1.000000" />
<sequence id="sequence_197" name="MACS_peak_770" length="100" weight="1.000000" />
<sequence id="sequence_198" name="MACS_peak_619" length="100" weight="1.000000" />
<sequence id="sequence_199" name="MACS_peak_812" length="100" weight="1.000000" />
<sequence id="sequence_200" name="MACS_peak_787" length="100" weight="1.000000" />
<sequence id="sequence_201" name="MACS_peak_541" length="100" weight="1.000000" />
<sequence id="sequence_202" name="MACS_peak_330" length="100" weight="1.000000" />
<sequence id="sequence_203" name="MACS_peak_175" length="100" weight="1.000000" />
<sequence id="sequence_204" name="MACS_peak_1087" length="100" weight="1.000000" />
<sequence id="sequence_205" name="MACS_peak_791" length="100" weight="1.000000" />
<sequence id="sequence_206" name="MACS_peak_881" length="100" weight="1.000000" />
<sequence id="sequence_207" name="MACS_peak_1059" length="100" weight="1.000000" />
<sequence id="sequence_208" name="MACS_peak_669" length="100" weight="1.000000" />
<sequence id="sequence_209" name="MACS_peak_248" length="100" weight="1.000000" />
<sequence id="sequence_210" name="MACS_peak_762" length="100" weight="1.000000" />
<sequence id="sequence_211" name="MACS_peak_779" length="100" weight="1.000000" />
<sequence id="sequence_212" name="MACS_peak_813" length="100" weight="1.000000" />
<sequence id="sequence_213" name="MACS_peak_924" length="100" weight="1.000000" />
<sequence id="sequence_214" name="MACS_peak_831" length="100" weight="1.000000" />
<sequence id="sequence_215" name="MACS_peak_613" length="100" weight="1.000000" />
<sequence id="sequence_216" name="MACS_peak_342" length="100" weight="1.000000" />
<sequence id="sequence_217" name="MACS_peak_495" length="100" weight="1.000000" />
<sequence id="sequence_218" name="MACS_peak_615" length="100" weight="1.000000" />
<sequence id="sequence_219" name="MACS_peak_617" length="100" weight="1.000000" />
<sequence id="sequence_220" name="MACS_peak_629" length="100" weight="1.000000" />
<sequence id="sequence_221" name="MACS_peak_703" length="100" weight="1.000000" />
<sequence id="sequence_222" name="MACS_peak_842" length="100" weight="1.000000" />
<sequence id="sequence_223" name="MACS_peak_891" length="100" weight="1.000000" />
<sequence id="sequence_224" name="MACS_peak_723" length="100" weight="1.000000" />
<sequence id="sequence_225" name="MACS_peak_258" length="100" weight="1.000000" />
<sequence id="sequence_226" name="MACS_peak_693" length="100" weight="1.000000" />
<sequence id="sequence_227" name="MACS_peak_929" length="100" weight="1.000000" />
<sequence id="sequence_228" name="MACS_peak_521" length="100" weight="1.000000" />
<sequence id="sequence_229" name="MACS_peak_474" length="100" weight="1.000000" />
<sequence id="sequence_230" name="MACS_peak_290" length="100" weight="1.000000" />
<sequence id="sequence_231" name="MACS_peak_850" length="100" weight="1.000000" />
<sequence id="sequence_232" name="MACS_peak_206" length="100" weight="1.000000" />
<sequence id="sequence_233" name="MACS_peak_985" length="100" weight="1.000000" />
<sequence id="sequence_234" name="MACS_peak_1115" length="100" weight="1.000000" />
<sequence id="sequence_235" name="MACS_peak_839" length="100" weight="1.000000" />
<sequence id="sequence_236" name="MACS_peak_378" length="100" weight="1.000000" />
<sequence id="sequence_237" name="MACS_peak_711" length="100" weight="1.000000" />
<sequence id="sequence_238" name="MACS_peak_216" length="100" weight="1.000000" />
<sequence id="sequence_239" name="MACS_peak_385" length="100" weight="1.000000" />
<sequence id="sequence_240" name="MACS_peak_145" length="100" weight="1.000000" />
<sequence id="sequence_241" name="MACS_peak_213" length="100" weight="1.000000" />
<sequence id="sequence_242" name="MACS_peak_178" length="100" weight="1.000000" />
<sequence id="sequence_243" name="MACS_peak_875" length="100" weight="1.000000" />
<sequence id="sequence_244" name="MACS_peak_917" length="100" weight="1.000000" />
<sequence id="sequence_245" name="MACS_peak_299" length="100" weight="1.000000" />
<sequence id="sequence_246" name="MACS_peak_505" length="100" weight="1.000000" />
<sequence id="sequence_247" name="MACS_peak_454" length="100" weight="1.000000" />
<sequence id="sequence_248" name="MACS_peak_889" length="100" weight="1.000000" />
<sequence id="sequence_249" name="MACS_peak_909" length="100" weight="1.000000" />
<sequence id="sequence_250" name="MACS_peak_731" length="100" weight="1.000000" />
<sequence id="sequence_251" name="MACS_peak_705" length="100" weight="1.000000" />
<sequence id="sequence_252" name="MACS_peak_841" length="100" weight="1.000000" />
<sequence id="sequence_253" name="MACS_peak_478" length="100" weight="1.000000" />
<sequence id="sequence_254" name="MACS_peak_708" length="100" weight="1.000000" />
<sequence id="sequence_255" name="MACS_peak_830" length="100" weight="1.000000" />
<sequence id="sequence_256" name="MACS_peak_321" length="100" weight="1.000000" />
<sequence id="sequence_257" name="MACS_peak_409" length="100" weight="1.000000" />
<sequence id="sequence_258" name="MACS_peak_752" length="100" weight="1.000000" />
<sequence id="sequence_259" name="MACS_peak_607" length="100" weight="1.000000" />
<sequence id="sequence_260" name="MACS_peak_272" length="100" weight="1.000000" />
<sequence id="sequence_261" name="MACS_peak_13" length="100" weight="1.000000" />
<sequence id="sequence_262" name="MACS_peak_1032" length="100" weight="1.000000" />
<sequence id="sequence_263" name="MACS_peak_999" length="100" weight="1.000000" />
<sequence id="sequence_264" name="MACS_peak_108" length="100" weight="1.000000" />
<sequence id="sequence_265" name="MACS_peak_954" length="100" weight="1.000000" />
<sequence id="sequence_266" name="MACS_peak_706" length="100" weight="1.000000" />
<sequence id="sequence_267" name="MACS_peak_849" length="100" weight="1.000000" />
<sequence id="sequence_268" name="MACS_peak_863" length="100" weight="1.000000" />
<sequence id="sequence_269" name="MACS_peak_720" length="100" weight="1.000000" />
<sequence id="sequence_270" name="MACS_peak_517" length="100" weight="1.000000" />
<sequence id="sequence_271" name="MACS_peak_46" length="100" weight="1.000000" />
<sequence id="sequence_272" name="MACS_peak_475" length="100" weight="1.000000" />
<sequence id="sequence_273" name="MACS_peak_242" length="100" weight="1.000000" />
<sequence id="sequence_274" name="MACS_peak_329" length="100" weight="1.000000" />
<sequence id="sequence_275" name="MACS_peak_609" length="100" weight="1.000000" />
<sequence id="sequence_276" name="MACS_peak_348" length="100" weight="1.000000" />
<sequence id="sequence_277" name="MACS_peak_86" length="100" weight="1.000000" />
<sequence id="sequence_278" name="MACS_peak_307" length="100" weight="1.000000" />
<sequence id="sequence_279" name="MACS_peak_337" length="100" weight="1.000000" />
<sequence id="sequence_280" name="MACS_peak_834" length="100" weight="1.000000" />
<sequence id="sequence_281" name="MACS_peak_516" length="100" weight="1.000000" />
<sequence id="sequence_282" name="MACS_peak_1073" length="100" weight="1.000000" />
<sequence id="sequence_283" name="MACS_peak_734" length="100" weight="1.000000" />
<sequence id="sequence_284" name="MACS_peak_699" length="100" weight="1.000000" />
<sequence id="sequence_285" name="MACS_peak_45" length="100" weight="1.000000" />
<sequence id="sequence_286" name="MACS_peak_794" length="100" weight="1.000000" />
<sequence id="sequence_287" name="MACS_peak_951" length="100" weight="1.000000" />
<sequence id="sequence_288" name="MACS_peak_1107" length="100" weight="1.000000" />
<sequence id="sequence_289" name="MACS_peak_527" length="100" weight="1.000000" />
<sequence id="sequence_290" name="MACS_peak_262" length="100" weight="1.000000" />